"""wine tasting scores and images

Revision ID: 57808958d92e
Revises: 8439cfdfd1e4
Create Date: 2026-09-22 10:55:52.405084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57808958d92e'
down_revision = '8439cfdfd1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wine_tasting_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasting_id', sa.Integer(), nullable=False),
    sa.Column('taster_name', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tasting_id'], ['wine_tasting_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wine_tasting_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=100), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine_tasting_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=True))
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image')

    op.drop_table('wine_tasting_scores')
    # ### end Alembic commands ###
